// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsK9Y6g5IzZ78V86wbTJCKxIFoiczh8-Y',
    appId: '1:349497357539:web:fd4af36b241e42fdf1c1d6',
    messagingSenderId: '349497357539',
    projectId: 'mynotes-flutter-armalik',
    authDomain: 'mynotes-flutter-armalik.firebaseapp.com',
    storageBucket: 'mynotes-flutter-armalik.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeFxS4-xYJrAtLRqpUEpZh6yy3h1Dnfso',
    appId: '1:349497357539:android:39f5b3a40e00e491f1c1d6',
    messagingSenderId: '349497357539',
    projectId: 'mynotes-flutter-armalik',
    storageBucket: 'mynotes-flutter-armalik.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk6_G3C2V48GkYIUJDm2vcWEmk8Z8oWxc',
    appId: '1:349497357539:ios:a68b37166c015cb2f1c1d6',
    messagingSenderId: '349497357539',
    projectId: 'mynotes-flutter-armalik',
    storageBucket: 'mynotes-flutter-armalik.appspot.com',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk6_G3C2V48GkYIUJDm2vcWEmk8Z8oWxc',
    appId: '1:349497357539:ios:a68b37166c015cb2f1c1d6',
    messagingSenderId: '349497357539',
    projectId: 'mynotes-flutter-armalik',
    storageBucket: 'mynotes-flutter-armalik.appspot.com',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsK9Y6g5IzZ78V86wbTJCKxIFoiczh8-Y',
    appId: '1:349497357539:web:949da689233bea87f1c1d6',
    messagingSenderId: '349497357539',
    projectId: 'mynotes-flutter-armalik',
    authDomain: 'mynotes-flutter-armalik.firebaseapp.com',
    storageBucket: 'mynotes-flutter-armalik.appspot.com',
  );
}
